#!/bin/bash
# VRX Hackathon - Quick Start Script
# Copy commands from this script into separate terminals

echo "=========================================="
echo "🚤 VRX HACKATHON - QUICK START"
echo "=========================================="
echo ""
echo "📋 SETUP (Run once per terminal):"
echo "----------------------------------------"
echo "cd /home/mazhar/vrx_ws"
echo "source /opt/ros/jazzy/setup.bash"
echo "source install/setup.bash"
echo ""
echo ""
echo "🚀 TERMINAL 1: Launch VRX Simulation"
echo "----------------------------------------"
echo "cd /home/mazhar/vrx_ws"
echo "source /opt/ros/jazzy/setup.bash"
echo "source install/setup.bash"
echo "ros2 launch vrx_gz vrx_environment.launch.py world:=sydney_regatta sim_mode:=full"
echo ""
echo "⏳ Wait 10-15 seconds for Gazebo to load..."
echo ""
echo ""
echo "🔍 TERMINAL 2: Verify Topics"
echo "----------------------------------------"
echo "cd /home/mazhar/vrx_ws"
echo "source /opt/ros/jazzy/setup.bash"
echo "source install/setup.bash"
echo "ros2 topic list"
echo ""
echo "# Check GPS:"
echo "ros2 topic echo /wamv/sensors/gps/gps/fix"
echo ""
echo "# Check Pose:"
echo "ros2 topic echo /wamv/pose"
echo ""
echo ""
echo "🤖 TERMINAL 3: Launch Autonomy"
echo "----------------------------------------"
echo "cd /home/mazhar/vrx_ws"
echo "source /opt/ros/jazzy/setup.bash"
echo "source install/setup.bash"
echo "ros2 run wamv_autonomy autonomy_node"
echo ""
echo ""
echo "🌐 TERMINAL 4: Launch rosbridge (for web dashboard)"
echo "----------------------------------------"
echo "# First install: sudo apt install ros-jazzy-rosbridge-suite"
echo "cd /home/mazhar/vrx_ws"
echo "source /opt/ros/jazzy/setup.bash"
echo "source install/setup.bash"
echo "ros2 launch rosbridge_server rosbridge_websocket_launch.xml"
echo ""
echo ""
echo "📊 TERMINAL 5: Create Web Dashboard"
echo "----------------------------------------"
echo "cd /home/mazhar/final_stand"
echo "npx create-react-app wamv-dashboard"
echo "cd wamv-dashboard"
echo "npm install rosbridge-client leaflet react-leaflet"
echo ""
echo ""
echo "=========================================="
echo "✅ READY TO GO!"
echo "=========================================="
echo ""
echo "📖 Full guide: /home/mazhar/final_stand/vrx/COMPLETE_SETUP_GUIDE.md"
echo ""

