#!/bin/bash

echo "🚀 Complete OpenCPN Integration Setup"
echo "====================================="
echo ""

# Source ROS
source /opt/ros/jazzy/setup.bash 2>/dev/null
if [ -f ~/vrx_ws/install/setup.bash ]; then
    source ~/vrx_ws/install/setup.bash
fi

echo "📋 This script will guide you through the complete setup"
echo ""
echo "You need 5 terminals open. This script will help you start each component."
echo ""
read -p "Press Enter to continue..."

echo ""
echo "=========================================="
echo "TERMINAL 1: VRX/Gazebo"
echo "=========================================="
echo "Run this command:"
echo "  cd ~/vrx_ws"
echo "  source /opt/ros/jazzy/setup.bash"
echo "  source install/setup.bash"
echo "  ros2 launch vrx_gz competition.launch.py world:=sydney_regatta"
echo ""
read -p "Press Enter when VRX is starting (wait 30 seconds for it to load)..."

echo ""
echo "=========================================="
echo "TERMINAL 2: NMEA Bridge (GPS → OpenCPN)"
echo "=========================================="
echo "Run this command:"
echo "  cd ~/final_stand/vrx/opencpn"
echo "  source /opt/ros/jazzy/setup.bash"
echo "  source ~/vrx_ws/install/setup.bash"
echo "  python3 nmea_bridge.py"
echo ""
read -p "Press Enter when NMEA bridge is running..."

echo ""
echo "=========================================="
echo "TERMINAL 3: Route Listener (OpenCPN → ROS)"
echo "=========================================="
echo "Run this command:"
echo "  cd ~/final_stand/vrx/opencpn"
echo "  source /opt/ros/jazzy/setup.bash"
echo "  source ~/vrx_ws/install/setup.bash"
echo "  python3 opencpn_route_listener.py"
echo ""
read -p "Press Enter when route listener is running..."

echo ""
echo "=========================================="
echo "TERMINAL 4: Autonomy Node"
echo "=========================================="
echo "Run this command:"
echo "  cd ~/vrx_ws"
echo "  source /opt/ros/jazzy/setup.bash"
echo "  source install/setup.bash"
echo "  ros2 launch wamv_autonomy autonomy.launch.py"
echo ""
read -p "Press Enter when autonomy node is running..."

echo ""
echo "=========================================="
echo "TERMINAL 5: OpenCPN"
echo "=========================================="
echo "Run this command:"
echo "  opencpn"
echo ""
read -p "Press Enter when OpenCPN is open..."

echo ""
echo "=========================================="
echo "CONFIGURE OPENCPN"
echo "=========================================="
echo ""
echo "Connection 1: Receive GPS (Input)"
echo "  - Options → Connections → Add Connection"
echo "  - Protocol: UDP"
echo "  - Address: 127.0.0.1"
echo "  - Port: 10110"
echo "  - Direction: Input"
echo "  - Show NMEA Debug Window: ✓"
echo ""
echo "Connection 2: Send Route (Output)"
echo "  - Options → Connections → Add Connection"
echo "  - Protocol: UDP"
echo "  - Address: 127.0.0.1"
echo "  - Port: 10111"
echo "  - Direction: Output"
echo "  - Filter: ECAPB,ECRMB,ECRMC,ECXTE"
echo ""
read -p "Press Enter when OpenCPN is configured..."

echo ""
echo "=========================================="
echo "✅ SETUP COMPLETE!"
echo "=========================================="
echo ""
echo "Now in OpenCPN:"
echo "  1. Verify boat position appears on map"
echo "  2. Draw route: Right-click → Mark → Create waypoints"
echo "  3. Create route: Right-click first waypoint → 'Create Route'"
echo "  4. Activate route: Right-click route → 'Activate Route'"
echo "  5. Watch Terminal 3 - should show 'New waypoint' messages"
echo "  6. Watch Gazebo - boat should start moving!"
echo ""
echo "📚 See CORRECTED_ARCHITECTURE.md for details"
echo ""

